// Assignment constants
export const FETCH_ASSIGNMENTS_REQUEST = 'FETCH_ASSIGNMENTS_REQUEST';
export const FETCH_ASSIGNMENTS_SUCCESS = 'FETCH_ASSIGNMENTS_SUCCESS';
export const FETCH_ASSIGNMENTS_FAILURE = 'FETCH_ASSIGNMENTS_FAILURE';

export const FETCH_TEACHER_ASSIGNMENTS_REQUEST = 'FETCH_TEACHER_ASSIGNMENTS_REQUEST';
export const FETCH_TEACHER_ASSIGNMENTS_SUCCESS = 'FETCH_TEACHER_ASSIGNMENTS_SUCCESS';
export const FETCH_TEACHER_ASSIGNMENTS_FAILURE = 'FETCH_TEACHER_ASSIGNMENTS_FAILURE';
